/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('../../old_code/DateFilter copy 2.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('../../old_code/DateFilter copy.vue')['default']
    DateFilter: typeof import('./components/DateFilter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
