/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AboutPage': RouteRecordInfo<'/AboutPage', '/AboutPage', Record<never, never>, Record<never, never>>,
    '/HelpPage': RouteRecordInfo<'/HelpPage', '/HelpPage', Record<never, never>, Record<never, never>>,
    '/league-table': RouteRecordInfo<'/league-table', '/league-table', Record<never, never>, Record<never, never>>,
    '/match/[id]': RouteRecordInfo<'/match/[id]', '/match/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/team-stats': RouteRecordInfo<'/team-stats', '/team-stats', Record<never, never>, Record<never, never>>,
  }
}
